### ISSUE TITLE
Getting a Serverless error, "Invalid PageToken", when SES Templates synchronize

### ISSUE THREAD

**Issue by Chebsi** [haftahave/serverless-ses-template#31] opened 2022-05-18 14:11 UTC
Hi there, 

I have a Serverless app that has a lot of SES templates to sync.

When the workflow is doing `listEmailTemplates` (10 at a time) we get a PageToken for each time. In a successful deploy that goes 24 times, but in the past few days we have been getting an Invalid PageToken error almost every deploy. This happens seemingly randomly, as sometimes it happens on the 10th time, sometimes on the 5th one. Sometimes the deploy will be successful and have no PageToken errors, although that can take several retries.

Any suggestions on debugging or troubleshooting this issue? E.g. is there some setting I can try out?

Edit: Like the first commenter, we are on version `4.0.4` of `@haftahave/serverless-ses-template` as well.

Our config looks like this:
```
  sesTemplates:
    addStage: true
    configFile: './src/api/email-templates/index.js'
```

Below are the SES Synchronization part of the deploy logs (let me know if you need more info...)
It stops on the 5th `listEmailTemplates` although we should have 24 iterations in a successful deploy. 

Note: in my logs I replaced the actual tokens with shorter names 'token-1', 'token-2', etc... 

```
.
.
.
previous logs (let me know if you need them)
.
.
.
```

```
Serverless: [AWS cloudformation 200 0.099s 0 retries] deleteChangeSet({
  StackName: 'project_name-automation-bootstrap',
  ChangeSetName: 'serverless-bootstrap-e7c0267a12f6df1ed8da730c8c1f34de05c60476'
})
Serverless: SesTemplate: AWS SES template synchronization...
Serverless: [AWS sesv2 200 0.087s 0 retries] listEmailTemplates({ PageSize: 10, NextToken: undefined })
Serverless: [AWS sesv2 200 0.08s 0 retries] listEmailTemplates({
  PageSize: 10,
  NextToken: 'token-1'
})
Serverless: [AWS sesv2 200 0.117s 0 retries] listEmailTemplates({
  PageSize: 10,
  NextToken: 'token-2'
})
Serverless: [AWS sesv2 200 0.104s 0 retries] listEmailTemplates({
  PageSize: 10,
  NextToken: 'token-3'
})
Serverless: [AWS sesv2 200 0.087s 0 retries] listEmailTemplates({
  PageSize: 10,
  NextToken: 'token-4'
})
Serverless: [AWS sesv2 400 0.075s 0 retries] listEmailTemplates({
  PageSize: 10,
  NextToken: 'token-5'
}) 

Serverless Error ----------------------------------------

ServerlessError: BadRequestException: Invalid PageToken <token-5>.
      at Object.extractError (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/protocol/json.js:52:27)
      at Request.extractError (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
      at Request.callListeners (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/request.js:686:14)
      at Request.transition (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/request.js:688:12)
      at Request.callListeners (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/request.js:686:14)
      at Request.transition (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/request.js:688:12)
      at Request.callListeners (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/home/runner/work/project_name/project_name/node_modules/aws-sdk/lib/event_listeners.js:335:13)
      at IncomingMessage.emit (events.js:412:35)
      at IncomingMessage.emit (domain.js:475:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
  ----------------------------------------------------------------------------------------------------
      at /home/runner/work/project_name/project_name/node_modules/serverless/lib/aws/request.js:226:11
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async persistentRequest (/home/runner/work/project_name/project_name/node_modules/serverless/lib/aws/request.js:150:14)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.19.3
     Framework Version:         2.72.3 (local)
     Plugin Version:            5.5.4
     SDK Version:               4.3.2
     Components Version:        3.18.2
 
Error: Process completed with exit code 1.
```

**Comment by krushetss** [comment] 2022-05-18 14:45
Hey, The same issue here with version "4.0.4"
```
Serverless: SesTemplate: AWS SES template synchronization...
Serverless: [AWS sesv2 200 0.074s 0 retries] listEmailTemplates({ PageSize: 10, NextToken: undefined })
Serverless: [AWS sesv2 400 0.061s 0 retries] listEmailTemplates({
  PageSize: 10,
  NextToken: 'AAAAAAAAAAH2X4qVcX2Y5n8IdLh6wKM8+YaGgRu8YJexAe74ZAj8s8qI5XSP/Cg14cohxPzEpVwYaqNxlq0Yalph4JUWb9FPOkyOAEb15kyPQjV6f/akH9xXUQ/9XS3cxnszUdlz/b2WD+xS7moVUgrffK+vXwfmFNBYpxTl//sC76x1RhxtbvEJr3U4LR/DRyrFWGOkm81AHtFJTzZRUnDkuNnn8GUMEjTVmkcqRYehSECoWqo5cBO77pKiqV+mk1YAojl9OXXfB/6mhnFKdmQ7fJRxVd/wjXSqaDizwQNIGUsRJ5buWdyzyO1d+7dirHKClNpORBg4BgbjdBiRoptDwOdLpkEjUg/P5VkKh+1/a5eh+uKULpv3GjA01CBUbe+NByOHgK2TKcKerNAl3rt/VXzS//MS8k6Z72NROZKYCEMyYJMCkzwLouEKkv6M4c7yBs45mv528lDiw0y9zRa1PN5SDJNhdZCszvQnh5QP935SDLdrnaxXcBsmJdmPLtTm1hE8nllOWf+ylPnAX1NnXpPiC29I/jk1RMuG6sxMeoxjgWN0TVVL9qE7zs9aAZg8SPBaTtNR0LLmfLhffrBX1kWm+IAhZWcThE5yCX8KBSzQSKoCe54ZU/MzmqSvhMlzW1g+RcUiWr+qfLrw8G/NjA/vEcAR1mri7fgLJUDpmhZZOoVqvZ1m0kOd47M3rhzpHq/ydS5WEx8mlv/MScCAZlR/U7m6FaLB5kBZqOps4Lt/vS6Za+FselVWs1Z9V+MHPMTJ+EYhRPDi/0TEBoc1QO6ZRv1fqzN0PKgVuzV/AU4K5gtksT+RlNYh4xBAmESzEh7v273TtX+4u3xlzUtgGnaHwn2ACDYIzwD3vVBn2W/kg46ydge/Xdgh4PC4un9pgluUP6FlIcCchNHYM+J5EVJq68RB4l/znJLw4X9ZeX/ncRtucO7NxIn26NvdThg+ZFqyX/a8p9I39SiPRVNgR8WuHvxpk6/40U6Ooszf4OgdLuv6xGlYLCuT4YOHpNJGxDqwSQyPaP2qmNwclIcNJpRS4PaeDqN/eVeyyeZZRPqlz3JfYsXq6x4o3pgcyuYGUGpcplOMiCbbpuTq6nXZrG1ERO7ZKXy1DWtCcInZAO0C6dOjsPXe3995cwS80vEXQK0xNZ9k+KV0tf0EOfW72OzKGmu+lxkaKYEHaVoGiWs2qM5AgA=='
})
 
 Serverless Error ----------------------------------------
 
  ServerlessError: BadRequestException: Invalid PageToken <AAAAAAAAAAH2X4qVcX2Y5n8IdLh6wKM8+YaGgRu8YJexAe74ZAj8s8qI5XSP/Cg14cohxPzEpVwYaqNxlq0Yalph4JUWb9FPOkyOAEb15kyPQjV6f/akH9xXUQ/9XS3cxnszUdlz/b2WD+xS7moVUgrffK+vXwfmFNBYpxTl//sC76x1RhxtbvEJr3U4LR/DRyrFWGOkm81AHtFJTzZRUnDkuNnn8GUMEjTVmkcqRYehSECoWqo5cBO77pKiqV+mk1YAojl9OXXfB/6mhnFKdmQ7fJRxVd/wjXSqaDizwQNIGUsRJ5buWdyzyO1d+7dirHKClNpORBg4BgbjdBiRoptDwOdLpkEjUg/P5VkKh+1/a5eh+uKULpv3GjA01CBUbe+NByOHgK2TKcKerNAl3rt/VXzS//MS8k6Z72NROZKYCEMyYJMCkzwLouEKkv6M4c7yBs45mv528lDiw0y9zRa1PN5SDJNhdZCszvQnh5QP935SDLdrnaxXcBsmJdmPLtTm1hE8nllOWf+ylPnAX1NnXpPiC29I/jk1RMuG6sxMeoxjgWN0TVVL9qE7zs9aAZg8SPBaTtNR0LLmfLhffrBX1kWm+IAhZWcThE5yCX8KBSzQSKoCe54ZU/MzmqSvhMlzW1g+RcUiWr+qfLrw8G/NjA/vEcAR1mri7fgLJUDpmhZZOoVqvZ1m0kOd47M3rhzpHq/ydS5WEx8mlv/MScCAZlR/U7m6FaLB5kBZqOps4Lt/vS6Za+FselVWs1Z9V+MHPMTJ+EYhRPDi/0TEBoc1QO6ZRv1fqzN0PKgVuzV/AU4K5gtksT+RlNYh4xBAmESzEh7v273TtX+4u3xlzUtgGnaHwn2ACDYIzwD3vVBn2W/kg46ydge/Xdgh4PC4un9pgluUP6FlIcCchNHYM+J5EVJq68RB4l/znJLw4X9ZeX/ncRtucO7NxIn26NvdThg+ZFqyX/a8p9I39SiPRVNgR8WuHvxpk6/40U6Ooszf4OgdLuv6xGlYLCuT4YOHpNJGxDqwSQyPaP2qmNwclIcNJpRS4PaeDqN/eVeyyeZZRPqlz3JfYsXq6x4o3pgcyuYGUGpcplOMiCbbpuTq6nXZrG1ERO7ZKXy1DWtCcInZAO0C6dOjsPXe3995cwS80vEXQK0xNZ9k+KV0tf0EOfW72OzKGmu+lxkaKYEHaVoGiWs2qM5AgA==>.
      at Object.extractError (/tmp/seed/source/node_modules/aws-sdk/lib/protocol/json.js:52:27)
      at Request.extractError (/tmp/seed/source/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
      at Request.callListeners (/tmp/seed/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/tmp/seed/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/tmp/seed/source/node_modules/aws-sdk/lib/request.js:686:14)
      at Request.transition (/tmp/seed/source/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/tmp/seed/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /tmp/seed/source/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/tmp/seed/source/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/tmp/seed/source/node_modules/aws-sdk/lib/request.js:688:12)
      at Request.callListeners (/tmp/seed/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/tmp/seed/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/tmp/seed/source/node_modules/aws-sdk/lib/request.js:686:14)
      at Request.transition (/tmp/seed/source/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/tmp/seed/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /tmp/seed/source/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/tmp/seed/source/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/tmp/seed/source/node_modules/aws-sdk/lib/request.js:688:12)
      at Request.callListeners (/tmp/seed/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/tmp/seed/source/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/tmp/seed/source/node_modules/aws-sdk/lib/event_listeners.js:335:13)
      at IncomingMessage.emit (events.js:326:22)
      at IncomingMessage.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
  ----------------------------------------------------------------------------------------------------
      at /tmp/seed/source/node_modules/serverless/lib/aws/request.js:225:11
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.22.2
     Framework Version:         2.65.0 (local)
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.17.2
```

**Comment by Enase** [comment] 2022-05-18 18:17
on it, just wait

**Comment by Enase** [comment] 2022-05-18 19:44
@Chebsi and @krushetss  Thanks for report!
I believe it should be fixed now. Please try new new release [4.0.5](https://github.com/haftahave/serverless-ses-template/releases/tag/4.0.5) and let me know if it helps.

**Comment by Enase** [comment] 2022-05-18 20:00
If it doesn't help, try to rollback to 4.0.4 and set [SLS_AWS_REQUEST_MAX_RETRIES](https://github.com/serverless/serverless/blob/main/CHANGELOG.md#1751-2020-07-16) environment variable to something above zero (4 i a good value IMHO). I would recommend to set it for your deploy builds independent on your results of testing.

**Comment by Enase** [comment] 2022-05-18 20:03
would be great if you will test both cases. thanks in advance

**Comment by Enase** [comment] 2022-05-18 21:47
@gsutcliffe how many templates do you have?

**Comment by gsutcliffe** [comment] 2022-05-18 21:49
@Enase 190 templates.

**Comment by Enase** [comment] 2022-05-18 21:54
@gsutcliffe I've executed `sls ses-template list` with 300+ templates without any issues. I've tested a few times deploy and list for sls v2 and v3. I need a way to reproduce it. What is your aws region? any information that might help are welcome.

**Comment by krushetss** [comment] 2022-05-19 12:38
@Enase Thanks a lot. Updated to 4.0.5 and for now, it seems like works for me. But this issue is not constant. Will get back to you if face this thing again.

**Comment by gsutcliffe** [comment] 2022-05-19 13:30
@Enase At least in my case I'm not confident this is a `serverless-ses-template` issue.  When using AWS-CLI I'm randomly seeing the "Invalid PageToken" when trying to get my template list.  I've set options for `--no-paginate`, `no-cli-pager` and `no-cli-auto-prompt` which did not help.  Considering this error is seen both locally and in our pipelines we're affected in multiple locations.  It's possibly account related considering you're not having these issues.  

`$ aws ses list-templates

An error occurred (InvalidParameterValue) when calling the ListTemplates operation: Invalid PageToken <AAAAAAAAAAE+zGSQhAKZRTcC7oNmb9vgmUQGtXw4zV7QyaFiv1aDtCCW/Dirr90bNFa4LXntc/ZtMxMy8lp9oTH8uI1S9hvrVMnh24V728U1Ui+rinKvSRVuq1wo3WjazcE9CzPTizUkukxil/FVIyK4RDcAG2SU5oTE4Pl1nXalEX6728Mr6czOd89KDjzgC6/fYgMiYNMSqN+iUMVcZXp3mexUmg2pcGUeX4O1ED3ELOhxcEl8ug0H9kKkyYYg/NjilTimNUDAS5U2zTf8D9m6G+mTc5aWLyxTphwAbJ3TdY50lCYVC4mR5Vl09V9s/j/xE3m95wrbE1UdWxFh+GGj6UrHaUoIVliiq/+Y4O83d4mZySYXQH+kIjnS12mb3KOBT5XD7yiSrAcYZR/CZNKsFTNiBzNKUIyu0jBl1Lz3rgT6QdaLtnXNgd7Yx1Qlg3i6jIEwTn/JoF/V6F1Ofbq1tTVa599QYFwBVCO3TS9EU6s2e28OuF65L07FwJ6JKW0K6dqS1DZ3sPJkH1K57VPdYtV8OAQLIjsp9iyAcwehXcPvwFfTOTv/2s7aCEIc3umHS5x25JYNiCedXS9qWBjZbFFGU6bgb/cUR+Uo3aiX9pF4kmSyZFbcK887wQ3oWQgCMVRIr1/WYbSNwnuRJvcT9K0avcvwuusGXnTC85YnfX5rpPwM12o7KXGfDRx5JhDdlmS/Qk+8HwtTBDJc2v+culgD7gsPbUBjcE0lAzvasKVYTDwfXe1YXsZlfmlNXMul1dN5x6KPyj2mHIOxlhpUG760QX72rtFOU2HVLLUWWvsr8D4jRj3F4OUdP27r0iocO79xtaWhuif4yMLEh9qNNZVnZ42YBkCdtVKED4mRAvuM0upFOIwog0Xn5IUdvz73P7P9AaatSRS6CSkQF99P8T35SMc52T93Ow3RffxBV/YHXoalMHHtRCjDMEPjSLsEmMxzMPwnhbcg7HDt8+X7vGaqJllnalmV6RDM9KXO4rauuf+SimxkOr8KYNM3EtvSlaCAC6tNTyGPXc8vcnnzW+G9qpE/IP7Y0XdwpZbkBERicNggcwXAbIeE7NrEpIyRbAX4iWy9VY/lzBJSWj1xg8UKbvR+5XpEyZpwa1bhmMplzlRN5P4KQWbLMCmxRM+kPpttovrmx9+vnmTob1sgJufLXwI3oXr2I+VToU7M4ZnLAJc5xw==>.`

**Comment by Enase** [comment] 2022-05-19 14:41
**Current solution:** Move your templates to `us-west-2` region

**Comment by Enase** [comment] 2022-06-03 11:31
@gsutcliffe Yes, it works now. Looks like AWS resolved it, at least I hope. I will rollback changes I did next release.

**Closed by Enase** 2022-06-03 11:31 UTC
